[project]
name = "mine-guide"
version = "0.1.0"
description = "An agent guide in Minecraft."
authors = [
    {name = "MeTMD"}
]
license = "GPL-3.0"
readme = "README.md"
requires-python = ">=3.9,<3.14"
dependencies = [
    "javascript (>=1!1.2,<1!2.0)",
    "ustb-openai (>=1.0.0,<2.0.0)",
    "openai (>=1.76.2,<2.0.0)"
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
toml = "0.10.2"
pyinstaller = "6.12.0"

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"
